[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "hF42rUUnXiwZHKPJg5v3fsAF2cybonVNen8VGsAetEg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/junkyung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
